name: Firebase Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install NodeJS
      run: |
        npm install -g firebase-tools
        npm install -g firebase-functions@latest firebase-admin@latest
    - name: Firebase Deploy
      run: firebase deploy --token "${{ secrets.FIREBASE_TOKEN }}"
